# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aff0309788f16c758310ba486f5820943ccf6f3e6f5041a75316ce7be3c6b684dd43f1f1ac4da207e0557190766a3291532fcf07355e83c9417f1b6ebd72c3c8

test:
  secret_key_base: 1a8a793992926de573ea4bc3f43bf052339662d58cb1acd28ee394b8e565c672f83ddf097be36f8f04b5a84a2a5c354a76e271faec91c97953828adc4920de80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
